#
# https://github.com/P3TERX/Actions-OpenWrt
#
# File: .github/workflows/update-checker.yml
# Description: Source code update checker
#
# Copyright (c) 2019-2026 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#

name: Update Checker

env:
  OPENWRT_REPO: https://github.com/openwrt/openwrt
  OPENWRT_BRANCH: main
  PACKAGES_REPO: https://github.com/openwrt/packages
  LUCI_REPO: https://github.com/openwrt/luci
  ROUTING_REPO: https://github.com/openwrt/routing
  
on:
  workflow_dispatch:
  schedule:
    - cron: '0,30 * * * 6,0'
    - cron: '0,30 17-23 * * 1-5'
      timezone: 'Asia/Shanghai'
    
jobs:
  check:
    runs-on: ubuntu-slim

    steps:
      - name: Get Commit Hash
        id: getHash
        run: |
          echo "openwrt=$(git ls-remote ${{ env.OPENWRT_REPO }} ${{ env.OPENWRT_BRANCH }} | cut -f1)" >> $GITHUB_OUTPUT
          echo "packages=$(git ls-remote ${{ env.PACKAGES_REPO }} HEAD | cut -f1)" >> $GITHUB_OUTPUT
          echo "luci=$(git ls-remote ${{ env.LUCI_REPO }} HEAD | cut -f1)" >> $GITHUB_OUTPUT
          echo "routing=$(git ls-remote ${{ env.ROUTING_REPO }} HEAD | cut -f1)" >> $GITHUB_OUTPUT

      - name: Compare Commit Hash
        id: cacheHash
        uses: actions/cache@v5
        with:
          path: .commitHash
          key: update-checker-${{ steps.getHash.outputs.openwrt }}-${{ steps.getHash.outputs.packages }}-${{ steps.getHash.outputs.luci }}-${{ steps.getHash.outputs.routing }}

      - name: Save New Hash
        if: steps.cacheHash.outputs.cache-hit != 'true'
        run: |
          mkdir -p .commitHash
          echo "${{ steps.getHash.outputs.openwrt }}" > .commitHash/openwrt
          echo "${{ steps.getHash.outputs.packages }}" > .commitHash/packages
          echo "${{ steps.getHash.outputs.luci }}" > .commitHash/luci
          echo "${{ steps.getHash.outputs.routing }}" > .commitHash/routing
          cat .commitHash/*

      - name: Trigger Build
        if: steps.cacheHash.outputs.cache-hit != 'true'
        uses: peter-evans/repository-dispatch@v4
        with:
          token: ${{ github.token }}
          event-type: Source Code Update
          client-payload: |
            {
              "reason": "Source Code Update",
              "openwrt_hash": "${{ steps.getHash.outputs.openwrt }}",
              "packages_hash": "${{ steps.getHash.outputs.packages }}",
              "luci_hash": "${{ steps.getHash.outputs.luci }}",
              "routing_hash": "${{ steps.getHash.outputs.routing }}"
            }

      - name: Delete old workflow runs
        uses: xiechangan123/delete-workflow-runs@main
        with:
          retain_days: 0
          keep_minimum_runs: 2
